// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repository.Models
{
    public partial class Eyeglass
    {
        [Key]
        public int EyeglassesId { get; set; }
        [Required]
        [StringLength(100)]
        public string EyeglassesName { get; set; }
        [StringLength(250)]
        public string EyeglassesDescription { get; set; }
        [StringLength(50)]
        public string FrameColor { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? Price { get; set; }
        public int? Quantity { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(30)]
        public string LensTypeId { get; set; }

        [ForeignKey("LensTypeId")]
        [InverseProperty("Eyeglasses")]
        public virtual LensType LensType { get; set; }
    }
}